name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.Socket4Bukkit
author: Hazae41
commands:
    sock:
        description: "Main Command"
        aliases: [bukkitsock]